# -*- coding: utf-8 -*-
"""week 8 odessya task, my_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vm9ZNFAHyA2AHDLk96w1huxEqyZDcaog
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
data = pd.read_csv(url)

data.tail(25)

df = data.dropna(subset=['Age']) #checking for missing data in the more important age column
len(df) #after cleaning data from missing data

df.head(15)

df.to_csv('titanic_df.csv', index=False)

selected_features  =  ['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

fig, axs  = plt.subplots(1, len(selected_features), figsize = (20,3))

for ax, f in zip(axs, selected_features):
    ax.hist(df[f], bins=5, color='skyblue', edgecolor='black')
    ax.set_xlabel(f)